[package]
name = "puniyu_library"
version = "0.1.0"
authors.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
futures = "0.3.31"
libloading = "0.8.9"

puniyu_logger = { workspace = true }
thiserror = { workspace = true }