[package]
name = "puniyu_task_derive"
version = "0.1.0"
authors.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies]
croner = { version = "3.0.0" }

convert_case.workspace = true
quote.workspace = true
syn.workspace = true
proc-macro2.workspace = true

puniyu_derive_utils = { path = "../puniyu_derive_utils" }
