[package]
name = "puniyu"
version = "0.1.0"
authors.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
log = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }

puniyu_core = { path = "../puniyu_core" }
puniyu_utils = { path = "../puniyu_utils" }
puniyu_registry = { path = "../puniyu_registry" }
puniyu_logger = { path = "../puniyu_logger" }
puniyu_plugin = { path = "../puniyu_plugin_test", package = "puniyu_plugin_test" }
libloading = "0.8.8"

[lints]
workspace = true

[[bin]]
name = "puniyu"
path = "src/main.rs"
