[package]
name = "puniyu_plugin_test"
version = "0.1.0"
authors.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
puniyu_plugin = { path = "../../puniyu_plugin" }
puniyu_core = { path = "../../puniyu_core" }


[build-dependencies]
puniyu_build = { path = "../../crates/puniyu_build" }


[features]
default = []
cdylib = []