[package]
name = "puniyu_registry"
version = "0.1.0"
authors.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
inventory = "0.3.21"
tokio = { version = "1.47.1", features = ["rt"] }
hashbrown = "0.16.0"
libloading = "0.8.8"
thiserror = { version = "2.0.16" }
puniyu_logger = { path = "../puniyu_logger" }
puniyu_macro = { path = "../puniyu_macro" }
log = "0.4.27"


[lints]
workspace = true
