[package]
name = "puniyu_core"
version = "0.1.0"
authors.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
notify = "8.2.0"
figlet-rs = "0.1.5"
convert_case = "0.8.0"
serde_json = "1.0.64"

serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
inventory = { workspace = true }

puniyu_logger = { workspace = true }
puniyu_registry = { path = "../puniyu_registry" }
puniyu_plugin_derive = { path = "../puniyu_derives/puniyu_plugin_derive" }
puniyu_adapter_derive = { path = "../puniyu_derives/puniyu_adapter_derive" }
puniyu_utils = { path = "../puniyu_utils" }
puniyu_server = { workspace = true }


[build-dependencies]
puniyu_build = { path = "../puniyu_build" }

[features]
default = ["server"]
server = []
core_preview = ["puniyu_build/core_preview"]
