[package]
name = "puniyu_core"
version = "0.1.0"
authors.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = "1.0.143"
log = { workspace = true }
thiserror = "2.0.16"
notify = "8.2.0"
strum = { version = "0.27.2", features = ["derive"] }
tokio = "1.47.1"

puniyu_system_info = { version = "0.5.0" }
puniyu_logger = { workspace = true }
puniyu_registry = { path = "../puniyu_registry" }
puniyu_utils = { path = "../puniyu_utils" }

[build-dependencies]
puniyu_build = { path = "../puniyu_build" }

[features]
core_preview = ["puniyu_build/core_preview"]
