[package]
name = "puniyu_utils"
version = "0.1.0"
authors.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
toml = { version = "0.9.5" }
puniyu_system_info = { version = "0.6.1", features = ["gpu"] }

serde.workspace = true
thiserror.workspace = true





