name: Label PRs

on:
  pull_request_target:
    types:
      - opened
  issues:
    types:
      - opened

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: 获取token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: 添加标签
        uses: srvaroa/labeler@master
        with:
          config_path: .github/labeler.yaml
          use_local_config: false
          fail_on_error: false
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
